# Generated by Django 3.2.9 on 2021-11-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
