# Generated by Django 3.2.9 on 2021-12-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='information',
            new_name='Shop_Information',
        ),
    ]
