# Generated by Django 3.2.8 on 2021-11-18 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20211118_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='title',
        ),
    ]
