# Generated by Django 3.2.9 on 2021-12-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_rename_information_shop_information'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop_Information',
            new_name='information',
        ),
    ]
