# Generated by Django 3.2.9 on 2021-11-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20211130_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='page_descripton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicription', models.CharField(max_length=500)),
            ],
        ),
    ]
