# Generated by Django 3.2.8 on 2021-11-18 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_upload_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='upload',
            new_name='video',
        ),
    ]
