# Generated by Django 3.2.9 on 2021-11-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_page_descripton'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aguas',
            new_name='menu',
        ),
        migrations.DeleteModel(
            name='preview_smoothie',
        ),
        migrations.DeleteModel(
            name='Smoothie',
        ),
        migrations.DeleteModel(
            name='Snacks',
        ),
    ]
