# Generated by Django 3.2.9 on 2021-11-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20211129_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='imggal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgTitle', models.CharField(max_length=100)),
                ('imgDsec', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
