# Generated by Django 3.2.9 on 2021-11-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20211130_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='desc',
        ),
    ]
