# Generated by Django 3.2.9 on 2021-11-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_remove_image_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=120)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='page_descripton',
        ),
    ]
