# Generated by Django 3.2.9 on 2021-11-30 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20211130_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tilte',
        ),
    ]
