# Generated by Django 3.2.9 on 2021-12-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_remove_image_tilte'),
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
